#!/bin/sh

# Clean up the results directory
rm -rf results
mkdir results

#Synthesize the Wrapper Files
echo 'Synthesizing XST wrapper file (core_top.vhd) with XST';
echo 'Synthesizing example design with XST';
xst -ifn xst.scr
cp system_ethernet_lite_wrapper_blk_mem_gen_v6_2_top.ngc ./results/


# Copy the netlist generated by Coregen
echo 'Copying files from the netlist directory to the results directory'
cp ../../system_ethernet_lite_wrapper_blk_mem_gen_v6_2.ngc results/

#  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
cp ../example_design/system_ethernet_lite_wrapper_blk_mem_gen_v6_2_top.ucf results/

cd results

echo 'Running ngdbuild'
ngdbuild -p xc6slx4-tqg144-3 system_ethernet_lite_wrapper_blk_mem_gen_v6_2_top

echo 'Running map'
map system_ethernet_lite_wrapper_blk_mem_gen_v6_2_top -o mapped.ncd -pr i

echo 'Running par'
par mapped.ncd routed.ncd

echo 'Running trce'
trce -e 10 routed.ncd mapped.pcf -o routed

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level VHDL model'
netgen -ofmt vhdl -sim -tm system_ethernet_lite_wrapper_blk_mem_gen_v6_2_top -pcf mapped.pcf -w routed.ncd routed.vhd
